name: demo_task
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Networking
  dio: ^5.1.2
  retrofit: ^4.0.1
  pretty_dio_logger: ^1.1.1
  http:

  # Connectivity
  connectivity_plus: ^4.0.0
  internet_connection_checker: ^1.0.0+1

  # Architecture
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1

  # Routing
  auto_route: ^7.1.0


  # Helpers
  enum_to_string: ^2.0.1
  intl: ^0.18.0
  jiffy: ^5.0.0
  sprintf: ^7.0.0
  collection: ^1.17.0

  # HTML and CSS render
  flutter_html: ^3.0.0-alpha.6
  webview_flutter: ^4.0.6
  flutter_inappwebview: ^5.7.2+3

  # Image Cache
  cached_network_image: ^3.2.3
  image_picker: ^0.8.6
  image_cropper: ^4.0.1

  # Permissions
  permission_handler: ^10.4.4

  # For UIs (clear what you don't need)
  gap: ^3.0.0
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  another_flushbar: ^1.12.29
  modal_bottom_sheet: ^3.0.0-pre
  flutter_native_splash: ^2.2.16
  pin_code_fields: ^7.4.0
  carousel_slider: ^4.2.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  blur: ^3.1.0
  photo_view: ^0.14.0
  badges: ^3.1.1

  # Validation
  rules: ^2.0.0

  # Code generation / annotations
  freezed: ^2.3.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  # Data storage
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^8.0.0
  hive: ^2.2.3
  dio_cache_interceptor_hive_store: ^3.2.2

  #  Firebase tracking & monitoring
  firebase_core: ^2.13.0
  firebase_core_platform_interface: ^4.8.0
  firebase_crashlytics: ^3.3.1
  firebase_performance: ^0.9.2+1
  firebase_messaging: ^14.6.1

  # Push Notifications
  notification_permissions: ^0.6.1
  plain_notification_token: ^0.0.4
  push: ^1.0.0

  # Application & Device Information
  package_info_plus: ^4.0.0
  device_info_plus: ^9.0.0

  # Misc. (Clear what yo don't need)
  infinite_scroll_pagination: ^4.0.0
  youtube_player_flutter: ^8.1.2
  flutter_rating_bar: ^4.0.1
  in_app_review: ^2.0.6
  store_redirect: ^2.0.1
  visibility_detector: ^0.4.0+2
  slider_button: ^2.0.0
  flutter_keyboard_visibility: ^5.4.1
  android_intent_plus: ^4.0.2
  readmore: ^2.2.0
  device_calendar: ^4.3.2
  percent_indicator: ^4.2.3
  url_launcher: ^6.1.10
  map_launcher: ^2.5.0+1
  qr_flutter: ^4.0.0
  animated_flip_counter: ^0.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  auto_route_generator:
  build_runner:
  retrofit_generator:

flutter:

  uses-material-design: true
  assets:
    - assets/
